/* tslint:disable */
/* eslint-disable */
/**
 * Orion Chamber User API
 * User endpoints for regular operations
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateVtonProcessDto
 */
export interface CreateVtonProcessDto {
    /**
     * Team ID (ObjectId)
     * @type {string}
     * @memberof CreateVtonProcessDto
     */
    'teamId': string;
    /**
     * Mannequin ID (ObjectId) or base64 uploaded image
     * @type {string}
     * @memberof CreateVtonProcessDto
     */
    'mannequin': string;
    /**
     * Base64 encoded garment image
     * @type {string}
     * @memberof CreateVtonProcessDto
     */
    'garment': string;
    /**
     * Type of garment (must be detected first using detect-garment-type endpoint)
     * @type {string}
     * @memberof CreateVtonProcessDto
     */
    'garmentType': CreateVtonProcessDtoGarmentTypeEnum;
    /**
     * Number of processing steps (affects quality and processing time)
     * @type {number}
     * @memberof CreateVtonProcessDto
     */
    'nSteps': number;
    /**
     * Optional manual mask as base64 image
     * @type {string}
     * @memberof CreateVtonProcessDto
     */
    'manuelMask'?: string;
    /**
     * Process visibility (me = only user, team = team members can see)
     * @type {string}
     * @memberof CreateVtonProcessDto
     */
    'visibility'?: CreateVtonProcessDtoVisibilityEnum;
}

export const CreateVtonProcessDtoGarmentTypeEnum = {
    Top: 'top',
    Bottom: 'bottom'
} as const;

export type CreateVtonProcessDtoGarmentTypeEnum = typeof CreateVtonProcessDtoGarmentTypeEnum[keyof typeof CreateVtonProcessDtoGarmentTypeEnum];
export const CreateVtonProcessDtoVisibilityEnum = {
    Me: 'me',
    Team: 'team'
} as const;

export type CreateVtonProcessDtoVisibilityEnum = typeof CreateVtonProcessDtoVisibilityEnum[keyof typeof CreateVtonProcessDtoVisibilityEnum];


