/* tslint:disable */
/* eslint-disable */
/**
 * Orion Chamber User API
 * User endpoints for regular operations
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GarmentTypeResponseDto
 */
export interface GarmentTypeResponseDto {
    /**
     * Detected garment type
     * @type {string}
     * @memberof GarmentTypeResponseDto
     */
    'garmentType': GarmentTypeResponseDtoGarmentTypeEnum;
}

export const GarmentTypeResponseDtoGarmentTypeEnum = {
    Top: 'TOP',
    Bottom: 'BOTTOM'
} as const;

export type GarmentTypeResponseDtoGarmentTypeEnum = typeof GarmentTypeResponseDtoGarmentTypeEnum[keyof typeof GarmentTypeResponseDtoGarmentTypeEnum];


