/* tslint:disable */
/* eslint-disable */
/**
 * Orion Chamber User API
 * User endpoints for regular operations
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TeamMemberDto } from './team-member-dto';

/**
 * 
 * @export
 * @interface GetTeamMembersResponseDto
 */
export interface GetTeamMembersResponseDto {
    /**
     * Success message
     * @type {string}
     * @memberof GetTeamMembersResponseDto
     */
    'message': string;
    /**
     * Team members list
     * @type {Array<TeamMemberDto>}
     * @memberof GetTeamMembersResponseDto
     */
    'members': Array<TeamMemberDto>;
}

