/* tslint:disable */
/* eslint-disable */
/**
 * Orion Chamber User API
 * User endpoints for regular operations
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TeamDto } from './team-dto';

/**
 * 
 * @export
 * @interface GetMyTeamsResponseDto
 */
export interface GetMyTeamsResponseDto {
    /**
     * Success message
     * @type {string}
     * @memberof GetMyTeamsResponseDto
     */
    'message': string;
    /**
     * User teams list
     * @type {Array<TeamDto>}
     * @memberof GetMyTeamsResponseDto
     */
    'teams': Array<TeamDto>;
}

