/* tslint:disable */
/* eslint-disable */
/**
 * Orion Chamber User API
 * User endpoints for regular operations
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserTeamInfoDto } from './user-team-info-dto';

/**
 * 
 * @export
 * @interface MeResponseDto
 */
export interface MeResponseDto {
    /**
     * User ID
     * @type {string}
     * @memberof MeResponseDto
     */
    'id': string;
    /**
     * User first name
     * @type {string}
     * @memberof MeResponseDto
     */
    'firstName': string;
    /**
     * User last name
     * @type {string}
     * @memberof MeResponseDto
     */
    'lastName': string;
    /**
     * User email address
     * @type {string}
     * @memberof MeResponseDto
     */
    'email': string;
    /**
     * Is user admin
     * @type {boolean}
     * @memberof MeResponseDto
     */
    'isAdmin': boolean;
    /**
     * Profile photo path
     * @type {string}
     * @memberof MeResponseDto
     */
    'profilePhoto'?: string;
    /**
     * Teams user is member of
     * @type {Array<UserTeamInfoDto>}
     * @memberof MeResponseDto
     */
    'teams': Array<UserTeamInfoDto>;
}

