/* tslint:disable */
/* eslint-disable */
/**
 * Orion Chamber User API
 * User endpoints for regular operations
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TeamMemberDto
 */
export interface TeamMemberDto {
    /**
     * Member ID
     * @type {string}
     * @memberof TeamMemberDto
     */
    'id': string;
    /**
     * Team ID
     * @type {string}
     * @memberof TeamMemberDto
     */
    'teamID': string;
    /**
     * User ID
     * @type {string}
     * @memberof TeamMemberDto
     */
    'userID': string;
    /**
     * Maximum credit limit for user
     * @type {number}
     * @memberof TeamMemberDto
     */
    'maxCredit': number;
    /**
     * Credit period type
     * @type {string}
     * @memberof TeamMemberDto
     */
    'creditPeriod': TeamMemberDtoCreditPeriodEnum;
    /**
     * Member creation date
     * @type {string}
     * @memberof TeamMemberDto
     */
    'createdAt': string;
}

export const TeamMemberDtoCreditPeriodEnum = {
    Monthly: 'MONTHLY',
    Weekly: 'WEEKLY'
} as const;

export type TeamMemberDtoCreditPeriodEnum = typeof TeamMemberDtoCreditPeriodEnum[keyof typeof TeamMemberDtoCreditPeriodEnum];


