/* tslint:disable */
/* eslint-disable */
/**
 * Orion Chamber User API
 * User endpoints for regular operations
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TeamDto } from './team-dto';

/**
 * 
 * @export
 * @interface UpdateTeamResponseDto
 */
export interface UpdateTeamResponseDto {
    /**
     * Success message
     * @type {string}
     * @memberof UpdateTeamResponseDto
     */
    'message': string;
    /**
     * Updated team data
     * @type {TeamDto}
     * @memberof UpdateTeamResponseDto
     */
    'team': TeamDto;
}

