/* tslint:disable */
/* eslint-disable */
/**
 * Orion Chamber User API
 * User endpoints for regular operations
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileDto } from './user-profile-dto';

/**
 * 
 * @export
 * @interface UpdateProfileResponseDto
 */
export interface UpdateProfileResponseDto {
    /**
     * Success message
     * @type {string}
     * @memberof UpdateProfileResponseDto
     */
    'message': string;
    /**
     * Updated user data
     * @type {UserProfileDto}
     * @memberof UpdateProfileResponseDto
     */
    'user': UserProfileDto;
}

