/* tslint:disable */
/* eslint-disable */
/**
 * Orion Chamber User API
 * User endpoints for regular operations
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VtonProcessResponseDto
 */
export interface VtonProcessResponseDto {
    /**
     * Process ID
     * @type {string}
     * @memberof VtonProcessResponseDto
     */
    'id': string;
    /**
     * User ID who created the process
     * @type {string}
     * @memberof VtonProcessResponseDto
     */
    'userID': string;
    /**
     * Team ID
     * @type {string}
     * @memberof VtonProcessResponseDto
     */
    'teamID': string;
    /**
     * Process type
     * @type {string}
     * @memberof VtonProcessResponseDto
     */
    'type': VtonProcessResponseDtoTypeEnum;
    /**
     * Current process status
     * @type {string}
     * @memberof VtonProcessResponseDto
     */
    'status': VtonProcessResponseDtoStatusEnum;
    /**
     * Process visibility
     * @type {string}
     * @memberof VtonProcessResponseDto
     */
    'visibility': VtonProcessResponseDtoVisibilityEnum;
    /**
     * Credits consumed by this process
     * @type {number}
     * @memberof VtonProcessResponseDto
     */
    'credit': number;
    /**
     * Process creation date
     * @type {string}
     * @memberof VtonProcessResponseDto
     */
    'createdAt': string;
    /**
     * VTON input parameters
     * @type {object}
     * @memberof VtonProcessResponseDto
     */
    'vtonInput': object;
    /**
     * VTON output (only when completed)
     * @type {object}
     * @memberof VtonProcessResponseDto
     */
    'vtonOutput'?: object;
}

export const VtonProcessResponseDtoTypeEnum = {
    Vton: 'VTON'
} as const;

export type VtonProcessResponseDtoTypeEnum = typeof VtonProcessResponseDtoTypeEnum[keyof typeof VtonProcessResponseDtoTypeEnum];
export const VtonProcessResponseDtoStatusEnum = {
    Pending: 'PENDING',
    Inprogress: 'INPROGRESS',
    Completed: 'COMPLETED'
} as const;

export type VtonProcessResponseDtoStatusEnum = typeof VtonProcessResponseDtoStatusEnum[keyof typeof VtonProcessResponseDtoStatusEnum];
export const VtonProcessResponseDtoVisibilityEnum = {
    Me: 'ME',
    Team: 'TEAM'
} as const;

export type VtonProcessResponseDtoVisibilityEnum = typeof VtonProcessResponseDtoVisibilityEnum[keyof typeof VtonProcessResponseDtoVisibilityEnum];


