/* tslint:disable */
/* eslint-disable */
/**
 * Orion Chamber Admin API
 * Admin-only endpoints for system management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AdminUserDto
 */
export interface AdminUserDto {
    /**
     * User ID
     * @type {string}
     * @memberof AdminUserDto
     */
    'id': string;
    /**
     * User first name
     * @type {string}
     * @memberof AdminUserDto
     */
    'firstName': string;
    /**
     * User last name
     * @type {string}
     * @memberof AdminUserDto
     */
    'lastName': string;
    /**
     * User email address
     * @type {string}
     * @memberof AdminUserDto
     */
    'email': string;
    /**
     * Is user admin
     * @type {boolean}
     * @memberof AdminUserDto
     */
    'isAdmin': boolean;
    /**
     * Profile photo path
     * @type {string}
     * @memberof AdminUserDto
     */
    'profilePhoto'?: string;
    /**
     * User creation date
     * @type {string}
     * @memberof AdminUserDto
     */
    'createdAt': string;
}

