/* tslint:disable */
/* eslint-disable */
/**
 * Orion Chamber Admin API
 * Admin-only endpoints for system management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeleteUserResponseDto
 */
export interface DeleteUserResponseDto {
    /**
     * Success message
     * @type {string}
     * @memberof DeleteUserResponseDto
     */
    'message': string;
}

