/* tslint:disable */
/* eslint-disable */
/**
 * Orion Chamber Admin API
 * Admin-only endpoints for system management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FileUploadDto
 */
export interface FileUploadDto {
    /**
     * 
     * @type {string}
     * @memberof FileUploadDto
     */
    'fileData': string;
    /**
     * 
     * @type {string}
     * @memberof FileUploadDto
     */
    'fileName': string;
    /**
     * 
     * @type {string}
     * @memberof FileUploadDto
     */
    'category': FileUploadDtoCategoryEnum;
    /**
     * 
     * @type {string}
     * @memberof FileUploadDto
     */
    'mimeType'?: string;
}

export const FileUploadDtoCategoryEnum = {
    Profiles: 'profiles',
    Garments: 'garments',
    Mannequins: 'mannequins',
    Results: 'results',
    Masks: 'masks'
} as const;

export type FileUploadDtoCategoryEnum = typeof FileUploadDtoCategoryEnum[keyof typeof FileUploadDtoCategoryEnum];


