/* tslint:disable */
/* eslint-disable */
/**
 * Orion Chamber Admin API
 * Admin-only endpoints for system management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FileInfoDto
 */
export interface FileInfoDto {
    /**
     * File path
     * @type {string}
     * @memberof FileInfoDto
     */
    'path': string;
    /**
     * Generated file name
     * @type {string}
     * @memberof FileInfoDto
     */
    'fileName': string;
    /**
     * Original file name
     * @type {string}
     * @memberof FileInfoDto
     */
    'originalName': string;
    /**
     * File category
     * @type {string}
     * @memberof FileInfoDto
     */
    'category': FileInfoDtoCategoryEnum;
    /**
     * File size in bytes
     * @type {number}
     * @memberof FileInfoDto
     */
    'size': number;
    /**
     * File access URL
     * @type {string}
     * @memberof FileInfoDto
     */
    'url': string;
}

export const FileInfoDtoCategoryEnum = {
    Profiles: 'profiles',
    Garments: 'garments',
    Mannequins: 'mannequins',
    Results: 'results',
    Masks: 'masks'
} as const;

export type FileInfoDtoCategoryEnum = typeof FileInfoDtoCategoryEnum[keyof typeof FileInfoDtoCategoryEnum];


