/* tslint:disable */
/* eslint-disable */
/**
 * Orion Chamber Admin API
 * Admin-only endpoints for system management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AdminUserDto } from './admin-user-dto';

/**
 * 
 * @export
 * @interface GetAllUsersResponseDto
 */
export interface GetAllUsersResponseDto {
    /**
     * Success message
     * @type {string}
     * @memberof GetAllUsersResponseDto
     */
    'message': string;
    /**
     * Users list
     * @type {Array<AdminUserDto>}
     * @memberof GetAllUsersResponseDto
     */
    'users': Array<AdminUserDto>;
}

