/* tslint:disable */
/* eslint-disable */
/**
 * Orion Chamber Admin API
 * Admin-only endpoints for system management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserDataDto } from './user-data-dto';

/**
 * 
 * @export
 * @interface RegisterResponseDto
 */
export interface RegisterResponseDto {
    /**
     * Success message
     * @type {string}
     * @memberof RegisterResponseDto
     */
    'message': string;
    /**
     * User data
     * @type {UserDataDto}
     * @memberof RegisterResponseDto
     */
    'user': UserDataDto;
}

