/* tslint:disable */
/* eslint-disable */
/**
 * Orion Chamber Admin API
 * Admin-only endpoints for system management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TeamDto
 */
export interface TeamDto {
    /**
     * Team ID
     * @type {string}
     * @memberof TeamDto
     */
    'id': string;
    /**
     * Team name
     * @type {string}
     * @memberof TeamDto
     */
    'name': string;
    /**
     * Team photo path
     * @type {string}
     * @memberof TeamDto
     */
    'photo'?: string;
    /**
     * Team photo URL
     * @type {string}
     * @memberof TeamDto
     */
    'photoUrl'?: string;
    /**
     * Team leader ID
     * @type {string}
     * @memberof TeamDto
     */
    'leadID': string;
    /**
     * Total team credits
     * @type {number}
     * @memberof TeamDto
     */
    'totalCredits': number;
    /**
     * Team creation date
     * @type {string}
     * @memberof TeamDto
     */
    'createdAt': string;
}

