/* tslint:disable */
/* eslint-disable */
/**
 * Orion Chamber Admin API
 * Admin-only endpoints for system management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserTeamInfoDto
 */
export interface UserTeamInfoDto {
    /**
     * Team ID
     * @type {string}
     * @memberof UserTeamInfoDto
     */
    'id': string;
    /**
     * Team name
     * @type {string}
     * @memberof UserTeamInfoDto
     */
    'name': string;
    /**
     * Team photo path
     * @type {string}
     * @memberof UserTeamInfoDto
     */
    'photo'?: string;
    /**
     * Team photo URL
     * @type {string}
     * @memberof UserTeamInfoDto
     */
    'photoUrl'?: string;
    /**
     * Team leader ID
     * @type {string}
     * @memberof UserTeamInfoDto
     */
    'leadID': string;
    /**
     * Total team credits
     * @type {number}
     * @memberof UserTeamInfoDto
     */
    'totalCredits': number;
    /**
     * User max credit limit in this team
     * @type {number}
     * @memberof UserTeamInfoDto
     */
    'maxCredit': number;
    /**
     * User credit period
     * @type {string}
     * @memberof UserTeamInfoDto
     */
    'creditPeriod': UserTeamInfoDtoCreditPeriodEnum;
    /**
     * Is user the leader of this team
     * @type {boolean}
     * @memberof UserTeamInfoDto
     */
    'isLeader': boolean;
}

export const UserTeamInfoDtoCreditPeriodEnum = {
    Weekly: 'WEEKLY',
    Monthly: 'MONTHLY'
} as const;

export type UserTeamInfoDtoCreditPeriodEnum = typeof UserTeamInfoDtoCreditPeriodEnum[keyof typeof UserTeamInfoDtoCreditPeriodEnum];


